name: Build

permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Setup Cpp (C++ / C)
        uses: aminya/setup-cpp@v0.44.0

      - name: Install CMake
        run: sudo apt-get install cmake

      - name: Configure CMake
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build
