name: Build

permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install PNPM
      run: npm install --global pnpm

    - name: Install dependencies
      run: pnpm install

    - name: Build
      run: pnpm build

    - name: Run tests
      run: pnpm test
